server:
  port: 8081

dubbo:
  application:
    name: hello-service-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880
    threads: 100
    minThread: 20
    maxThread: 500
  timeout: 10000
  annotation:
    package: com.example.service